### ISSUE TITLE
vimpatch report

### ISSUE THREAD

**Issue by justinmk** [neovim/bot-ci#10]
We have an auto-generated vimpatch report:

http://neovim.org/doc/build-reports/vimpatch/

But there are some remaining tasks to do:
- [x] fix URLs to open PRs
- [x] link to GH commit
- [x] account for NA items
- [x] robustness against 8.0 switchover
- [x] use GH_TOKEN instead of anonymous

**Comment by jamessan** [comment]
>     * link to GH commit

We already link to the tree at the time of the tag, so we can either consider this resolved or we can change the link to `/releases/tag/vX.Y.ZZZZ`.

**Comment by justinmk** [comment]
many thanks @jamessan
