### ISSUE TITLE
improve git-related error handling

### ISSUE THREAD

**Issue by justinmk** [neovim/bot-ci#118]
(migrated from https://github.com/neovim/bot-ci/issues/12)

When `git push` fails, currently we keep retrying many times. Should not do that when GH_TOKEN is invalid, and possibly other errors where retrying is just a waste of time.

**Comment by acferreir4** [comment]
@justinmk Would it suffice to just remove the while/retry loop or should it be replaced with another mechanism for handling an invalid gh_token?

**Comment by justinmk** [comment]
@acferreir4 Not sure how often requests fail, but if it's more than zero then removing the retry loop will cause failed jobs.

[GitHub API doc](https://developer.github.com/v3/oauth_authorizations/#check-an-authorization) says it will return 404 in that case. So we only need to break out of the loop if 404 is returned.

Probably this can be done in `_check_gh_error`. https://github.com/neovim/bot-ci/blob/master/ci/common/github-api.sh

**Comment by dread-uo** [comment]
Hello! I'd like to tackle this issue; seems to be a nice start here.

Is the idea breaking from [this while](https://github.com/neovim/bot-ci/blob/master/ci/common/common.sh#L150) if the GH_TOKEN is invalid?

Thanks in advance!

**Comment by justinmk** [comment]
@dread-uo Thanks for the interest in helping! It looks like here it's already done: https://github.com/neovim/bot-ci/blob/c5cd1042b1047a2ec63f93b355c7e60543606aa9/ci/common/common.sh#L152

This hasn't been a problem in practice, so let's just close this issue.
