### ISSUE TITLE
remove dependency on apt.llvm.org

### ISSUE THREAD

**Issue by justinmk** [neovim/bot-ci#125]
(see https://github.com/neovim/bot-ci/pull/124#issuecomment-354657483 )

clang 5.0 seems to be the default on travis now (expand the "Build system information" section of the build log):

```
clang version
clang version 5.0.0 (tags/RELEASE_500/final)
```

We could try removing the apt.llvm.org source entirely (i.e. delete the `addons` directives: https://github.com/neovim/bot-ci/pull/124/files )

**Comment by jszakmeister** [comment]
I'm not arguing one way or the other, but this was done in the first place to make sure to gain access to the latest compilers.  Presumably, what's available on Travis will diverge and the apt repo will have something newer--clang 6.0 should become final on Feb 21st.

FWIW, if it's causing troubles with the Travis build, I'd just remove using apt.llvm.org entirely.

**Comment by justinmk** [comment]
@jszakmeister wasn't there a specific feature(s) that we needed (e.g. bug fixes in ASAN) that nudged us to use a newer clang version? Hopefully we can avoid that situation now.

**Comment by jszakmeister** [comment]
@justinmk There may have been, but I don't recall that.  What I remember the argument being was that hopefully new compilers do a better job at raising issues.  Like I said before, I honestly don't care one way or the other--I just wanted to point out what the rationale was (or at least what I recall it being). :-)
