### ISSUE TITLE
Marvim report change log for nightly builds

### ISSUE THREAD

**Issue by catskul** [neovim/bot-ci#148]
Marvim publishes nightly builds seen here:
https://github.com/neovim/neovim/releases/tag/nightly

And received by those subscribed. Unfortunately the info attached to those nightly builds is mostly unhelpful as it doesn't contain a change log. While manual changelog would be too much work simply a list of commits since the last nightly would be super helpful

**Comment by justinmk** [comment]
Note that this would essentially be a list of commits in the last 24 hours. That's not much difference than visiting https://github.com/neovim/neovim/commits/master .

What is the advantage and where would the changelog be posted if https://github.com/neovim/neovim/commits/master is not convenient enough?

**Comment by justinmk** [comment]
It should be pretty easy. Mainly I would not want the Releases page to get too big, GitHub already makes it difficult to find the "Assets" for a given release.
