### ISSUE TITLE
Missing the nighly package of MacOS depending on the order in which the jobs are processed

### ISSUE THREAD

**Issue by erw7** [neovim/bot-ci#152]
If a MacOS job uploads a package with a nightly build before a Linux job, the upload will fail. In this case, the following log is recorded.

```
Error uploading release assets: Validation Failed.
```

https://travis-ci.org/github/neovim/bot-ci/jobs/738720200#L11933

If a MacOS job uploads before a Linux job after the next day, the upload succeeds because the assets do not exist, but the Linux job deletes the package. That continues until the MacOS job is uploaded after the Linux job. I'm not sure why MacOS jobs have recently been terminated first, but this is why the MacOS nightly package is often missing.

The following changes might fix it, but I'm not familiar with the `nightly.sh` process, could someone confirm this?

```diff
diff --git a/ci/nightly.sh b/ci/nightly.sh
index b0a127a..1f6e960 100755
--- a/ci/nightly.sh
+++ b/ci/nightly.sh
@@ -230,13 +230,29 @@ upload_nightly() {
     "{ \"draft\": false, \"prerelease\": ${prerelease} }" \
     > /dev/null
 
-  if [ "${tag}" = nightly ] ; then
+  if [ "${tag}" = nightly  && "${delete_old}" = delete ] ; then
     log_info "upload_nightly: updating '${tag}' tag to: ${commit}"
     send_gh_api_data_request repos/${NEOVIM_REPO}/git/refs/tags/${tag} PATCH \
       "{ \"force\": true, \"sha\": \"${commit}\" }" \
       > /dev/null
   fi
 
+  if [ "${tag}" = nightly && "${delete_old}" != delete ] ; then
+    local retry=5
+    while :
+    do
+      is_tag_pointing_to nightly "${commit}"
+      if [ $? -eq 0 ] ; then
+        break;
+      fi
+      if [ $retry -eq 0 ] ; then
+        log_error 'The maximum number of attempts to wait for the deletion job to end has been reached' ; exit 1
+      fi
+      sleep 1m
+      retry=$(( $retry - 1 ))
+    done
+  fi
+
   log_info "upload_nightly: Uploading asset: $uploadname"
   upload_release_asset "$filepath" "$uploadname" ${NEOVIM_REPO} ${release_id} \
     > /dev/null
```

**Comment by jamessan** [comment]
If the problem is just that we need the macOS build to happen after the Linux one, wouldn't adding stages to the CI solve the problem better?

**Comment by erw7** [comment]
> If the problem is just that we need the macOS build to happen after the Linux one, wouldn't adding stages to the CI solve the problem better?

I've just read https://docs.travis-ci.com/user/build-stages/. I also think it's better to add a stage because it's simpler than modifying nightly.sh.
