### ISSUE TITLE
Remove sudo calls from scripts/travis-setup.sh

### ISSUE THREAD

**Issue by grtlr** [neovim/bot-ci#56]
For neovim/neovim#2340 we would have to remove all the sudo calls from the scripts that get called by TravisCI.

A sudo call is made in [scripts/travis-setup.sh](https://github.com/neovim/bot-ci/blob/master/scripts/travis-setup.sh#L21). Is it possible to remove this one, or do this in another way?

**Comment by justinmk** [comment]
https://github.com/neovim/bot-ci/commit/77345431b03efa352d7e93861a5e6fbd703197cb
