### ISSUE TITLE
bzr sync not working

### ISSUE THREAD

**Issue by fwalch** [neovim/bot-ci#59]
```
Importing http://bazaar.leonerd.org.uk/c/libvterm into Git branch libvterm-import.
Branched 646 revisions.
08:23:25 Calculating the revisions to include ...
08:23:25 Starting export of 675 revisions ...
08:23:26 Exported 675 revisions in 0:00:02
Fast-forwarding master to libvterm-import.
fatal: Not possible to fast-forward, aborting.
```

Something seems to have gone wrong with the import.. I see that Marvim was set as committer of the most recent commits in https://github.com/neovim/libvterm/commits/master, that's probably the issue.

**Comment by tarruda** [comment]
Maybe use `git bzr clone` followed by a push to the mirror? I think this is how I updated it:

```
git bzr clone ${BZR_REPO}
git remote add mirror git@github.com/neovim/${MIRROR}
git push mirror master
```

**Comment by tarruda** [comment]
Or simply remove the `--ff-only` option from `git merge --ff-only "${repo}-import"`
