### ISSUE TITLE
User docu font size too small.

### ISSUE THREAD

**Issue by fwalch** [neovim/bot-ci#72]
Apparently, something changed in the stylesheet and caused the user docu (neovim.io/doc/user) to have a really small font size. Leaving this here mostly as a reminder for myself to look into that.

As a side note, the doc_index Travis job seems to have problems lately. Maybe just because neovim.io now defaults to HTTPS.

**Comment by justinmk** [comment]
It's the bootstrap CSS. I've been meaning to fix it.

**Comment by fwalch** [comment]
Looks like this has been fixed; thanks @justinmk!
