### ISSUE TITLE
Have the nightly builds fallen over?

### ISSUE THREAD

**Issue by myitcv** [neovim/bot-ci#73]
At the time of writing:

![screen shot 2015-10-09 at 09 25 31](https://cloud.githubusercontent.com/assets/3374574/10389235/ced56d86-6e67-11e5-95bb-d6303f16e6a0.png)

Seems last nightly build was a few days ago.

**Comment by justinmk** [comment]
I just poked it. I need to check on the cron job.

**Comment by myitcv** [comment]
Thanks
