### ISSUE TITLE
Some travis targets are failing

### ISSUE THREAD

**Issue by tarruda** [neovim/bot-ci#74]
[report](https://travis-ci.org/neovim/bot-ci/builds/90297191)

- doc_index
- nightly
- clint-errors
- clang report
- deps64

I went looking for errors because I noticed https://neovim.io/doc/user/eval.html does not reflect the latest documentation(is the user documentation generated in this repo?).

@fwalch since you have more experience with this repo, could you investigate whats going on? I've looked into the doc_index error log and it fails with code 4. wget man page says this is the code of a network failure, but doesn't give any more details. I've tried updating all neovim.io URLs to https but it didn't help. I wonder if this is the same problem as https://github.com/neovim/neovim.github.io/issues/121

**Comment by fwalch** [comment]
@tarruda I'll try to look into it tomorrow.

**Comment by tarruda** [comment]
> @tarruda I'll try to look into it tomorrow.

No rush, I was just wanted to bring this into attention. If my guess is correctly and this is caused by cloudflare SSL version(which could very well by unsupported by ubuntu 12.04), we have two choices:

- modify the travis script to download a newer version of SSL and build wget with proper linkage
- modify cloudflare configuration to allow plain http.

**Comment by justinmk** [comment]
This is happening because shields.io now redirects to HTTPS always.

**Comment by justinmk** [comment]
All of these should be fixed now, except doc-index which I am moving to the `allow_failures` block in `.travis.yml` until SSL is fixed on travis. In the meantime the doc-index HTML file will need to be manually pushed to the `doc` repo.

**Comment by justinmk** [comment]
The doc-index build is fixed now also. 

Only thing left is coverity.
