### ISSUE TITLE
Ignore auto-generated code in clang report

### ISSUE THREAD

**Issue by fwalch** [neovim/bot-ci#88]
Lots of warnings like `Dead store	Dead initialization	build /src /nvim /auto /api /private /dispatch.` in https://neovim.io/doc/reports/clang/

**Comment by bfredl** [comment]
It could be my fault, in neovim/neovim#4934 I changed the cleanup logic, before that these initializations was actually used. I will look into fixing it later.

**Comment by fwalch** [comment]
And I would have just suppressed them... :sweat_smile: thanks!

**Comment by bfredl** [comment]
Well, the fix was simple in this case :)
